import { CaseStudy } from '@/types/portfolio';

export const caseStudies: CaseStudy[] = [
  {
    id: '1',
    slug: 'hyderabad-bistro-qr',
    title: 'Digital Menu & Ordering System for Local Cafe',
    clientName: 'Nizam Bistro',
    industry: 'Restaurant / Cafe',
    category: 'QR Systems',
    services: ['QR Menu Design', 'Order Management System', 'Table Analytics'],
    outcomeHeadline: 'Increased Table Turnover by 25% with Contactless Ordering',
    metricStatus: 'illustrative',
    thumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=1200',
    metrics: [
      { label: 'Order Processing Time', value: '-30%', isIllustrative: true },
      { label: 'Average Order Value', value: '+15%', isIllustrative: true },
      { label: 'Customer Satisfaction', value: '4.8/5', isIllustrative: true },
    ],
    content: {
      problem: 'Nizam Bistro was struggling with slow order taking during peak hours, leading to long wait times and occasional order errors. Their paper menus were also costly to update frequently.',
      solution: 'We deployed a comprehensive QR-based digital menu system. Customers can scan to view high-quality images of dishes, customize orders, and pay directly from their phones, completely bypassing the wait for a waiter.',
      results: 'The bistro saw immediate improvements in operational efficiency. Table turnover increased, and staff could focus more on food delivery and customer service rather than order taking.',
    },
    gallery: [
      'https://loremflickr.com/1200/800/restaurant,food?lock=1',
      'https://loremflickr.com/1200/800/restaurant,food?lock=2',
      'https://loremflickr.com/1200/800/restaurant,food?lock=3',
      'https://loremflickr.com/1200/800/restaurant,food?lock=4',
      'https://loremflickr.com/1200/800/restaurant,food?lock=5',
      'https://loremflickr.com/1200/800/restaurant,food?lock=6',
    ],
  },
  {
    id: '4',
    slug: 'fitness-app-social',
    title: 'Social Media Growth for Fitness Brand',
    clientName: 'IronCore Fitness',
    industry: 'Health & Fitness',
    category: 'Social Media',
    services: ['Content Strategy', 'Instagram Reels', 'Community Management'],
    outcomeHeadline: 'Grew Organic Instagram Following by 50k in 6 Months',
    metricStatus: 'illustrative',
    thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=1200',
    metrics: [
      { label: 'Follower Growth', value: '+50k', isIllustrative: true },
      { label: 'Engagement Rate', value: '8.5%', isIllustrative: true },
      { label: 'Lead Generation', value: '+300%', isIllustrative: true },
    ],
    content: {
      problem: 'IronCore Fitness had a great local presence but struggled to translate that into an engaging online community. Their content was inconsistent and lacked a clear visual identity.',
      solution: 'We developed a comprehensive social media strategy focusing on high-quality video content (Reels), educational posts, and community engagement. We also established a consistent brand voice and aesthetic.',
      results: 'The new strategy led to explosive organic growth on Instagram, significantly increasing brand awareness and driving a surge of new leads for their online coaching programs.',
    },
    gallery: [
      'https://loremflickr.com/1200/800/fitness,workout?lock=19',
      'https://loremflickr.com/1200/800/fitness,workout?lock=20',
      'https://loremflickr.com/1200/800/fitness,workout?lock=21',
      'https://loremflickr.com/1200/800/fitness,workout?lock=22',
      'https://loremflickr.com/1200/800/fitness,workout?lock=23',
      'https://loremflickr.com/1200/800/fitness,workout?lock=24',
    ],
  },
  {
    id: '6',
    slug: 'real-estate-platform',
    title: 'Luxury Property Search Platform',
    clientName: 'Horizon Estates',
    industry: 'Real Estate',
    category: 'Websites',
    services: ['Web Design', 'Full-stack Development', 'Property API Integration'],
    outcomeHeadline: 'Increased Lead Generation by 200% with Enhanced Search',
    metricStatus: 'illustrative',
    thumbnail: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=1200',
    metrics: [
      { label: 'Property Inquiries', value: '+200%', isIllustrative: true },
      { label: 'Time on Site', value: '+3.5m', isIllustrative: true },
      { label: 'Search Speed', value: '<0.5s', isIllustrative: true },
    ],
    content: {
      problem: 'Horizon Estates struggled with an antiquated property listing site that made it difficult for high-net-worth individuals to find luxury homes quickly. The mobile experience was practically non-existent.',
      solution: 'We built a custom Next.js web application with a heavily optimized map-based search, seamless high-resolution image galleries, and a CRM integration for rapid agent response.',
      results: 'The modernized platform significantly elevated the brand perception, leading to a massive increase in qualified inquiries and longer user engagement times.',
    },
    gallery: [
      'https://loremflickr.com/1200/800/mansion,realestate?lock=31',
      'https://loremflickr.com/1200/800/mansion,realestate?lock=32',
      'https://loremflickr.com/1200/800/mansion,realestate?lock=33',
      'https://loremflickr.com/1200/800/mansion,realestate?lock=34',
      'https://loremflickr.com/1200/800/mansion,realestate?lock=35',
      'https://loremflickr.com/1200/800/mansion,realestate?lock=36',
    ],
  },
  {
    id: '7',
    slug: 'boutique-hotel-branding',
    title: 'Brand Refresh for Heritage Hotel',
    clientName: 'The Monarch Retreat',
    industry: 'Hospitality',
    category: 'Branding',
    services: ['Brand Strategy', 'Visual Identity', 'Collateral Design'],
    outcomeHeadline: 'Elevated Brand Positioning Leading to 30% Higher Room Rates',
    metricStatus: 'illustrative',
    thumbnail: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=1200',
    metrics: [
      { label: 'Direct Bookings', value: '+45%', isIllustrative: true },
      { label: 'Average Daily Rate', value: '+30%', isIllustrative: true },
      { label: 'Guest Retention', value: '+15%', isIllustrative: true },
    ],
    content: {
      problem: 'The Monarch Retreat had a rich history but their visual identity felt dated, making it hard to justify premium pricing compared to newer, modern competitors in the area.',
      solution: 'We developed a sophisticated new brand identity that merged classic elegance with modern minimalism. This included a new logo, typography, color palette, and premium print collateral for the guest experience.',
      results: 'The rebrand successfully repositioned the hotel as a luxury destination. They were able to confidently increase their room rates while simultaneously seeing a boost in direct bookings.',
    },
    gallery: [
      'https://loremflickr.com/1200/800/hotel,resort?lock=37',
      'https://loremflickr.com/1200/800/hotel,resort?lock=38',
      'https://loremflickr.com/1200/800/hotel,resort?lock=39',
      'https://loremflickr.com/1200/800/hotel,resort?lock=40',
      'https://loremflickr.com/1200/800/hotel,resort?lock=41',
      'https://loremflickr.com/1200/800/hotel,resort?lock=42',
    ],
  },
  {
    id: '8',
    slug: 'event-ticketing-qr',
    title: 'Seamless QR Ticketing for Music Festival',
    clientName: 'Sonic Waves Festival',
    industry: 'Events / Entertainment',
    category: 'QR Systems',
    services: ['QR Ticket Generation', 'Access Control System', 'Real-time Analytics'],
    outcomeHeadline: 'Processed 15,000+ Attendees with Zero Gateway Downtime',
    metricStatus: 'illustrative',
    thumbnail: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&q=80&w=1200',
    metrics: [
      { label: 'Entry Speed', value: '3s/person', isIllustrative: true },
      { label: 'Fraudulent Tickets', value: '0%', isIllustrative: true },
      { label: 'Peak Scans/Min', value: '450', isIllustrative: true },
    ],
    content: {
      problem: 'Previous iterations of the Sonic Waves Festival suffered from massive bottlenecks at the entrance due to slow ticket scanning and issues with counterfeit paper tickets.',
      solution: 'We implemented a robust, cloud-synced QR ticketing system. Attendees received dynamic QR codes, and staff used our custom app for instant offline-capable scanning at the gates.',
      results: 'The entry process was incredibly smooth, eliminating the dreaded entrance queues. The real-time dashboard also provided organizers with crucial data on crowd flow and peak arrival times.',
    },
    gallery: [
      'https://loremflickr.com/1200/800/concert,event?lock=43',
      'https://loremflickr.com/1200/800/concert,event?lock=44',
      'https://loremflickr.com/1200/800/concert,event?lock=45',
      'https://loremflickr.com/1200/800/concert,event?lock=46',
      'https://loremflickr.com/1200/800/concert,event?lock=47',
      'https://loremflickr.com/1200/800/concert,event?lock=48',
    ],
  },
  {
    id: '12',
    slug: 'coffee-roasters-branding',
    title: 'Brand Identity for Artisanal Roastery',
    clientName: 'Elevate Coffee Co.',
    industry: 'Food & Beverage',
    category: 'Branding',
    services: ['Logo Design', 'Packaging Design', 'Brand Storytelling'],
    outcomeHeadline: 'Successfully Launched Premium Product Line in 50+ Stores',
    metricStatus: 'illustrative',
    thumbnail: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&q=80&w=1200',
    metrics: [
      { label: 'Retail Distribution', value: '+50 Stores', isIllustrative: true },
      { label: 'Brand Recognition', value: '+60%', isIllustrative: true },
      { label: 'Packaging Costs', value: '-15%', isIllustrative: true },
    ],
    content: {
      problem: 'Elevate Coffee Co. produced high-quality, ethically sourced beans, but their generic packaging failed to stand out on crowded supermarket shelves or convey their premium quality.',
      solution: 'We crafted a compelling brand story and translated it into a striking visual identity. We designed bespoke, sustainable packaging that featured custom illustrations highlighting the origin of each roast.',
      results: 'The new packaging was an instant hit. It helped Elevate secure shelf space in over 50 premium grocers and significantly boosted their direct-to-consumer online sales.',
    },
    gallery: [
      'https://loremflickr.com/1200/800/coffee,cafe?lock=67',
      'https://loremflickr.com/1200/800/coffee,cafe?lock=68',
      'https://loremflickr.com/1200/800/coffee,cafe?lock=69',
      'https://loremflickr.com/1200/800/coffee,cafe?lock=70',
      'https://loremflickr.com/1200/800/coffee,cafe?lock=71',
      'https://loremflickr.com/1200/800/coffee,cafe?lock=72',
    ],
  },
  {
    id: '13',
    slug: 'restaurant-chain-social',
    title: 'Social Media Strategy for Local Eatery',
    clientName: 'The Spice Trail',
    industry: 'Restaurant / Cafe',
    category: 'Social Media',
    services: ['Content Creation', 'Influencer Marketing', 'Ad Campaigns'],
    outcomeHeadline: 'Drove 20% Increase in Weekend Reservations via Instagram',
    metricStatus: 'illustrative',
    thumbnail: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=1200',
    metrics: [
      { label: 'Engagement Rate', value: '11%', isIllustrative: true },
      { label: 'Follower Growth', value: '+15k', isIllustrative: true },
      { label: 'Weekend Bookings', value: '+20%', isIllustrative: true },
    ],
    content: {
      problem: 'The Spice Trail had incredible food but minimal online presence. They relied heavily on walk-ins and word-of-mouth, missing out on a large audience of food enthusiasts on social media.',
      solution: 'We executed a visually rich social media campaign focused on high-quality food photography and behind-the-scenes chef videos. We also partnered with local food influencers for a tasting event.',
      results: 'The campaign generated significant buzz. Their Instagram following grew rapidly, and the targeted content directly resulted in a noticeable spike in reservations, particularly on weekends.',
    },
    gallery: [
      'https://loremflickr.com/1200/800/restaurant,dining?lock=73',
      'https://loremflickr.com/1200/800/restaurant,dining?lock=74',
      'https://loremflickr.com/1200/800/restaurant,dining?lock=75',
      'https://loremflickr.com/1200/800/restaurant,dining?lock=76',
      'https://loremflickr.com/1200/800/restaurant,dining?lock=77',
      'https://loremflickr.com/1200/800/restaurant,dining?lock=78',
    ],
  }
];

export function getCaseStudyBySlug(slug: string): CaseStudy | undefined {
  return caseStudies.find(study => study.slug === slug);
}
